### ISSUE TITLE
problems at installation with blockmodel.cc

### ISSUE THREAD

**Issue by arielolafsalgado** [junipertcy/det_k_bisbm#13]
Here is the full output of sh scripts/compile_engines.sh

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
-- Found Boost: /usr/include (found suitable version "1.58.0", minimum required is "1.40") found components: program_options 
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/olaf/Descargas/bipartiteSBM/engines/bipartiteSBM-MCMC
Scanning dependencies of target mcmc
[ 11%] Building CXX object src/CMakeFiles/mcmc.dir/mcmc_main.cc.o
[ 22%] Building CXX object src/CMakeFiles/mcmc.dir/metropolis_hasting.cc.o
[ 33%] Building CXX object src/CMakeFiles/mcmc.dir/output_functions.cc.o
[ 44%] Building CXX object src/CMakeFiles/mcmc.dir/graph_utilities.cc.o
[ 55%] Building CXX object src/CMakeFiles/mcmc.dir/blockmodel.cc.o
/home/olaf/Descargas/bipartiteSBM/engines/bipartiteSBM-MCMC/src/blockmodel.cc: In member function ‘void blockmodel_t::agg_merge(std::mt19937&, int, int)’:
/home/olaf/Descargas/bipartiteSBM/engines/bipartiteSBM-MCMC/src/blockmodel.cc:234:104: error: ‘blockmodel_t::bmove_’ is not a variable in clause ‘private’
/home/olaf/Descargas/bipartiteSBM/engines/bipartiteSBM-MCMC/src/blockmodel.cc:246:44: error: ‘blockmodel_t::bmoves_’ is not a variable in clause ‘shared’
src/CMakeFiles/mcmc.dir/build.make:134: fallo en las instrucciones para el objetivo 'src/CMakeFiles/mcmc.dir/blockmodel.cc.o'
make[2]: *** [src/CMakeFiles/mcmc.dir/blockmodel.cc.o] Error 1
CMakeFiles/Makefile2:113: fallo en las instrucciones para el objetivo 'src/CMakeFiles/mcmc.dir/all'
make[1]: *** [src/CMakeFiles/mcmc.dir/all] Error 2
Makefile:103: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2
scripts/compile_engines.sh: 4: cd: can't cd to engines/bipartiteSBM-KL/

**Comment by junipertcy** [comment]
There is an experimental OpenMP feature in the [MCMC engine](https://github.com/junipertcy/bipartiteSBM-MCMC/tree/openmp). And previously, bipartiteSBM was committed with that wrong branch. 

Could you try again @arielolafsalgado? Delete the whole repository and redo `git clone git@github.com:junipertcy/bipartiteSBM.git --recursive`. It should work.

**Comment by arielolafsalgado** [comment]
It worked! Great.
I also gave me a warning:

olaf@olaf:~/Dropbox/Parks/biSBM/bipartiteSBM$ sh scripts/compile_engines.sh 
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
-- Found Boost: /usr/include (found suitable version "1.58.0", minimum required is "1.40") found components: program_options 
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/olaf/Dropbox/Parks/biSBM/bipartiteSBM/engines/bipartiteSBM-MCMC
Scanning dependencies of target mcmc
[ 11%] Building CXX object src/CMakeFiles/mcmc.dir/mcmc_main.cc.o
[ 22%] Building CXX object src/CMakeFiles/mcmc.dir/metropolis_hasting.cc.o
[ 33%] Building CXX object src/CMakeFiles/mcmc.dir/output_functions.cc.o
[ 44%] Building CXX object src/CMakeFiles/mcmc.dir/graph_utilities.cc.o
[ 55%] Building CXX object src/CMakeFiles/mcmc.dir/blockmodel.cc.o
[ 66%] Building CXX object src/CMakeFiles/mcmc.dir/support/spence.cc.o
[ 77%] Building CXX object src/CMakeFiles/mcmc.dir/support/cache.cc.o
[ 88%] Building CXX object src/CMakeFiles/mcmc.dir/support/int_part.cc.o
[100%] Linking CXX executable ../bin/mcmc
[100%] Built target mcmc
/home/olaf/Dropbox/Parks/biSBM/bipartiteSBM
In file included from biSBM.cpp:37:0:
biSBM.h: In function ‘void PrintResults(std::__cxx11::string)’:
biSBM.h:1009:32: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
     chdir(saveLocation.c_str());

Don't know if you want to change something about it. 

Thanks a lot!

**Comment by junipertcy** [comment]
@arielolafsalgado Thank you!
