### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by eirinistam** [junipertcy/det_k_bisbm#7]
Hi!
When i run the following command line
sh scripts/compile_engines.sh
I receive this error:
cripts/compile_engines.sh: 3: scripts/compile_engines.sh: pushd: not found
scripts/compile_engines.sh: 4: scripts/compile_engines.sh: pushd: not found

Can you explain me why?
Thank you

**Comment by junipertcy** [comment]
@eirinistam Thanks for the note! Some systems do not have `pushd` or `popd` installed by default. I have fixed the issue with the latest commit.
